platform :ios, '9.0'
use_frameworks!
pod 'SDWebImage'
pod 'RealmSwift'
#pod 'Sleipnir'
pod 'KYDrawerController'
pod 'BFKit-Swift'
pod 'SVProgressHUD'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'CNPPopupController'
pod 'HMSegmentedControl'

source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'Alamofire', '~> 1.2'
