platform :ios, '9.1'

def myPods
  use_frameworks!
  pod 'RealmSwift'
  pod 'KYDrawerController'
  pod 'XLPagerTabStrip'
  pod 'JCTagListView'
  pod 'ActionSheetPicker-3.0'
end

target 'Immerse' do
  myPods
end